default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: '<%= ENV['DATABASE_USERNAME'] %>'
  password: '<%= ENV['TENURE_V1_DATABASE_PASSWORD'] %>'

development:
  <<: *default
  database: tenure_v1_development
  username: '<%= ENV['DATABASE_USERNAME'] %>'
  password: '<%= ENV['TENURE_V1_DATABASE_PASSWORD'] %>'
test:
  <<: *default
  database: tenure_v1_test
  username: '<%= ENV['DATABASE_USERNAME'] %>'
  password: '<%= ENV['TENURE_V1_DATABASE_PASSWORD'] %>'

production:
  <<: *default
  username: '<%= ENV['DATABASE_USERNAME'] %>'
  url: <%= ENV['DATABASE_URL'] %>